### ISSUE TITLE
[BUG] cannot import MultivariateGaussianDistribution etc. after update to 1.0.0

### ISSUE THREAD

**Issue by wengmingao** [jmschrei/pomegranate#1026]
**To Reproduce**

after update to 1.0.0, when use 

`from pomegranate import MultivariateGaussianDistribution, GeneralMixtureModel`

then

`ImportError: cannot import name 'MultivariateGaussianDistribution' from 'pomegranate' (/opt/conda/lib/python3.10/site-packages/pomegranate/__init__.py)`

after downgrade to pomegranate-0.14.8, everything is OK.

**Comment by jmschrei** [comment]
Use `Normal` instead. `Normal` takes in the parameter `covariance_type` which defaults to `full`.

**Comment by wengmingao** [comment]
Thanks for your help.
